* Removed firebase related as not needed for this service.

diff --git a/.github/workflows/CI.yaml b/.github/workflows/CI.yaml
--- a/.github/workflows/CI.yaml
+++ b/.github/workflows/CI.yaml
@@ -5,7 +5,7 @@ on:
 
 env:
   IMAGE_NAME: ghcr.io/nus-iss-projects/bit-scout-kafka-consume/bit-scout-backend-coin
-  DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
+  # DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
 
 jobs:
   build:
@@ -18,13 +18,13 @@ jobs:
 
     steps:
     - uses: actions/checkout@v3
-    - name: Retrieve firebase credentials
-      run: |
-          echo $DATA | base64 -di > app/google-services.json
-          if [ ! -f "app/google-services.json" ]; then
-            echo "Error: Firebase credentials file not found."
-            exit 1
-          fi
+    # - name: Retrieve firebase credentials
+    #   run: |
+    #       echo $DATA | base64 -di > app/google-services.json
+    #       if [ ! -f "app/google-services.json" ]; then
+    #         echo "Error: Firebase credentials file not found."
+    #         exit 1
+    #       fi
     - name: Set up JDK 17
       uses: actions/setup-java@v3
       with:
@@ -47,15 +47,15 @@ jobs:
       - uses: actions/checkout@v3
         with:
           fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
-      - name: Copy Firebase credentials file
-        env:
-          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
-        run: |
-          echo $DATA | base64 -di > app/google-services.json
-          if [ ! -f "app/google-services.json" ]; then
-            echo "Error: Firebase credentials file not found."
-            exit 1
-          fi
+      # - name: Copy Firebase credentials file
+      #   env:
+      #     DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
+      #   run: |
+      #     echo $DATA | base64 -di > app/google-services.json
+      #     if [ ! -f "app/google-services.json" ]; then
+      #       echo "Error: Firebase credentials file not found."
+      #       exit 1
+      #     fi
       - name: Set up JDK 17
         uses: actions/setup-java@v3
         with:
@@ -89,13 +89,13 @@ jobs:
         with:
           distribution: 'adopt'
           java-version: 17
-      - name: Retrieve firebase credentials
-        run: |
-          echo $DATA | base64 -di > app/google-services.json
-          if [ ! -f "app/google-services.json" ]; then
-            echo "Error: Firebase credentials file not found."
-            exit 1
-          fi    
+      # - name: Retrieve firebase credentials
+      #   run: |
+      #     echo $DATA | base64 -di > app/google-services.json
+      #     if [ ! -f "app/google-services.json" ]; then
+      #       echo "Error: Firebase credentials file not found."
+      #       exit 1
+      #     fi    
       - run: mvn clean install --batch-mode --errors --fail-at-end
       - name: Upload Artifacts
         uses: actions/upload-artifact@v3
